- name: Install cargo-binstall
  uses: cargo-bins/cargo-binstall@main
- name: Install wasm-pack
  run: cargo binstall wasm-pack -y --force
- name: Build livereload-client WASM
  run: wasm-pack build --target web crates/livereload-client
